---
# Secrets can be created via your selected devops platform or retrieved from Azure Key Vault at runtime
apiVersion: v1
kind: Secret
metadata:
  name: json-transformer-secret
  namespace: json-transformer
stringData:
  connectionString: MAIN_SB_CONNECTION_STRING
  keda-translator-sb-conn: DAPR_SB_CONNECTION_STRING
  ApplicationInsights__ConnectionString: APP_INSIGHTS_CONNECTION_STRING
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: json-transformer-svc-act
  namespace: json-transformer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keys-manager-role
  namespace: json-transformer
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  - configMaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: json-transformer-svc-act-keys-manager-rolebinding
  namespace: json-transformer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keys-manager-role
subjects:
- kind: ServiceAccount
  name: json-transformer-svc-act
---