apiVersion: v1
kind: ConfigMap
metadata:
  name: appsettings
  namespace: json-transformer
data:
  appsettings.json: |-
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft": "Warning",
          "Microsoft.Hosting.Lifetime": "Information"
        }
      },
      "ServerOptions": {
        "AppVersion": "V1.0"
      }
    }