---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: json-transformer-sb-deployment-scaled-object
  namespace: json-transformer
  labels:
    deploymentName: json-transformer-sb-deployment
spec:
  scaleTargetRef:
    name: json-transformer-sb-deployment
  pollingInterval: 30  # Optional. Default: 30 seconds
  cooldownPeriod:  300 # Optional. Default: 300 seconds
  minReplicaCount: 3   # Optional. Default: 0
  maxReplicaCount: 30 # Optional. Default: 100
  triggers:
  - type: azure-servicebus
    metadata:
      connectionFromEnv: keda-transformer-sb-conn
      topicName: d2c-messages 
      subscriptionName: json-transformer
      messageCount: '50' # This will be used to trigger a scale up operation when number of messages exceed this number
